### ISSUE TITLE
Change HTTP_HEAD var name

### ISSUE THREAD

**Issue by samuelcarreira** [sglahn/ESP8266-sensor-board-firmware#1]
Hi there, 
first of all, congrats for your project. Very well structured!

With the updated libraries there is a conflict with the var `HTTP_HEAD` declared on the **ConfigurationTemplate.h** file and the Arduino Core libraries.
You need to rename it to something like `HTTP_HEADER` to compile the project.

Also, do you customize the `"ESP8266httpUpdate.h"` file or do you use the original ESP8266 HTTP Update library? I am asking this because I saw the library included with quotes (not angle brackets) 

Thank you

**Comment by samuelcarreira** [comment]
Also, change the line 24 of the HttpServer.cpp file to the new variable name. Something like:
` String page = FPSTR(HTTP_HEADER);`

**Comment by sglahn** [comment]
Thx! I fixed the issues.
